# Generated by Django 3.1.7 on 2021-06-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='num',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='userid',
        ),
        migrations.AddField(
            model_name='excel',
            name='District',
            field=models.CharField(default='district name', max_length=30),
        ),
        migrations.AddField(
            model_name='excel',
            name='GA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='GO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='GT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='IBAvailable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='IBOccupied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='IBTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='O2A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='O2O',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='O2T',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='SNO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='VA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='VO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='VT',
            field=models.IntegerField(default=0),
        ),
    ]
