# Generated by Django 3.1.7 on 2021-06-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210630_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='n1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excel',
            name='n9',
            field=models.IntegerField(default=0),
        ),
    ]
