# Generated by Django 3.1.7 on 2021-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210630_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='n1',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n10',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n11',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n12',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n13',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n2',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n3',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n4',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n5',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n6',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n7',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n8',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='n9',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='excel',
            name='num',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
