# Generated by Django 3.2.4 on 2021-07-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210630_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
